### ISSUE TITLE
Update to FastText v0.9.1

### ISSUE THREAD

**Issue by carschno** [carschno/JFastText#4]
With the release of [FastText v0.9.1](https://github.com/facebookresearch/fastText/releases/tag/v0.9.1), JFastText needs to be updated.

Based on an [issue](https://github.com/vinhkhuc/JFastText/issues/56) reported on original JFastText repo.

**Comment by nirzohar** [comment]
Cannot compile 0.9.1 version. FastText using newer version of C++ which require std::sort_heap (in loss.cc line 71), so need to update the pom.xml.

**Comment by carschno** [comment]
@nirzohar just to clarify: are you referring to compiling FastText standalone, or within JFastText? Regarding the former, I have been able to compile v0.9.1 with c++ (GCC) 8.3.1 20190223, from 2018.

Within JFastText, I'm working on updating the wrapper to handle version 0.9.1.

**Comment by carschno** [comment]
@nirzohar The branch at https://github.com/carschno/JFastText/tree/fasttext_0.9.1 includes the latest FastText version and seems to work fine.
It depends on a fix on FastText whough which still needs to be merged (https://github.com/facebookresearch/fastText/pull/936). However, the branch should already work now.

Note that this does not (yet) fix the issue that this still does not work for Windows and Mac OSX (#5).

**Comment by nirzohar** [comment]
Thanks for the update.
________________________________

**Comment by jingcangcang** [comment]
@carschno hi, I find the result in terminal through "./fasttext predict" have different result with java class (jft.predictProba(text)), have you verified the results of this two ways?

**Comment by nirzohar** [comment]
Hey
Cannot remember, and I'm no longer into it.

Sorry
________________________________

**Comment by carschno** [comment]
> @carschno hi, I find the result in terminal through "./fasttext predict" have different result with java class (jft.predictProba(text)), have you verified the results of this two ways?

Hi @jingcangcang ,
Thanks for reporting this.

Could you report some more details on this in a dedicated issue. It would be important to know as many details as possible, at least:
- What are the numbers you see in either approach?
- How can you reproduce this?
